name: Build & Release

on:
  push:
    tags:
      - 'v*'  # e.g. v1.0.0, v2.1.3

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write  # Required for release creation

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Extract tag version
      id: version
      shell: pwsh
      run: |
        $version = $env:GITHUB_REF -replace 'refs/tags/', ''
        echo "VERSION=$version" >> $env:GITHUB_ENV


    - name: Prepare build dir
      shell: powershell
      run: |
        $dest = "${{ github.workspace }}\ApolloFleet"
        New-Item -ItemType Directory -Force -Path $dest
        Copy-Item -Path "${{ github.workspace }}\README.md" -Destination $dest
        Copy-Item -Path "${{ github.workspace }}\bin" -Destination $dest -Recurse

    - name: Compile AHK script
      uses: drajabr/Action-Ahk2Exe@main
      with:
        in: Apollo Fleet.ahk
        out: ${{ github.workspace }}/ApolloFleet/ApolloFleet.exe  # Use a fixed name during compilation
        icon: ${{ github.workspace }}/icons/9.ico
    
    - name: Create SFX Zip installer
      uses: drajabr/actions-7-zip-win@main
      with:
        in: ${{ github.workspace }}\ApolloFleet 
        out: ${{ github.workspace }}\ApolloFleet-${{ env.VERSION }}.exe
        options: a -sfx7z.sfx
  
    - name: Create Release and Upload Asset
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ env.VERSION }}
        files: |
          ApolloFleet-${{ env.VERSION }}.exe
        prerelease: false 
        generate_release_notes: true

#  TODO: keep exe name the same, but add it inside directory then zip it with version number
#        This could make it easier to keep settings file and config file inside one directory 
