name: Build

on:
  push:
    tags:
      - 'v*'  # Only run on version tags like v1.0.0

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract tag version
        shell: bash
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Compile AHK script
        uses: drajabr/Action-Ahk2Exe@main
        with:
          in: "${{ github.workspace }}/src/Apollo Fleet Launcher.ahk"
          out: "${{ github.workspace }}/ApolloFleet-${{ env.VERSION }}.exe"
          icon: "assets/9.png"

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ApolloFleet-${{ env.VERSION }}
          path: "${{ github.workspace }}/ApolloFleet-${{ env.VERSION }}.exe"
