name: Build

on:
  push:
    tags:
      - 'v*'  # e.g. v1.0.0, v2.1.3

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Extract tag version
      id: version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

    - name: Compile AHK script
      uses: CCCC-L/Action-Ahk2Exe@main
      with:
        in: "scrc/Apollo Fleet Launcher.ahk"
        out: "dist/ApolloFleet-Launcher.exe"
        icon: "assets/9.png"

    - name: Create zip archive with tag
      run: |
        cd dist
        powershell Compress-Archive -Path "ApolloFleet-Launcher.exe" -DestinationPath "ApolloFleet-Launcher-${{ env.VERSION }}.zip"

    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: ahk-zip-${{ env.VERSION }}
        path: dist/ApolloFleet-Launcher-${{ env.VERSION }}.zip
