name: Build

on:
  push:
    tags:
      - 'v*'  # e.g. v1.0.0, v2.1.3

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Extract tag version
      id: version
      run: echo "VERSION=$($env:GITHUB_REF -replace 'refs/tags/', '')" >> $env:GITHUB_ENV

    - name: Compile AHK script
      run: |
        & autohotkey\Ahk2Exe.exe /in "src/Apollo Fleet Launcher.ahk" `
        /out "dist/ApolloFleet-${Env:VERSION}.exe" `
        /icon "assets/9.png" `
        /base "${Env:BaseFile}"
        
    - name: List output files
      run: Get-ChildItem -Recurse dist

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: ApolloFleet-${{ env.VERSION }}
        path: dist/ApolloFleet-${{ env.VERSION }}.exe
