name: Build

on:
  push
  
jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Extract tag version
      id: version
      shell: pwsh
      run: |
        $version = $env:GITHUB_REF -replace 'refs/tags/', ''
        echo "VERSION=$version" >> $env:GITHUB_ENV

    - name: Compile AHK script
      uses: drajabr/Action-Ahk2Exe@main
      with:
        in: Apollo Fleet Launcher.ahk
        out: Apollo Fleet Launcher.exe

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: Apollo Fleet Launcher.exe
        path: Apollo Fleet Launcher.exe
