name: Build

on:
  push:
    tags:
      - 'v*'  # e.g. v1.0.0, v2.1.3

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Extract tag version
      id: version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

    - name: Compile AHK script
      uses: drajabr/Action-Ahk2Exe@main
      with:
        in: "src/Apollo Fleet Launcher.ahk"
        out: "dist/ApolloFleet-${{ env.VERSION }}.exe"
        icon: "assets/9.png"

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: ApolloFleet-${{ env.VERSION }}
        path: dist/ApolloFleet-${{ env.VERSION }}.exe
