name: Sync Binaries

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  sync:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run sync-platform-tools.ps1
        run: powershell -ExecutionPolicy Bypass -File bin/download-platform-tools.ps1

      - name: List downloaded files
        run: |
            echo "Files in /bin:"
            Get-ChildItem -Path bin -Recurse
        shell: pwsh
        
      - name: Commit and push updated binaries
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add bin/platform-tools
          git commit -m "Update platform-tools binaries [CI]" || echo "No changes to commit"
          git push