name: test

on:
  push

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write  # Required for release creation

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Extract tag version
      id: version
      shell: pwsh
      run: |
        $version = $env:GITHUB_SHA.Substring(0, 7)
        echo "VERSION=$version" >> $env:GITHUB_ENV

    - name: Compile AHK script
      uses: drajabr/Action-Ahk2Exe@main
      with:
        in: src/Apollo Fleet.ahk
        out: ${{ github.workspace }}/ApolloFleet/ApolloFleet.exe  # Use a fixed name during compilation
        icon: ${{ github.workspace }}/assets/9.ico

    - name: Download and install 7z
      uses: milliewalky/setup-7-zip@v2
    
    - name: Create SFX Zip installer
      uses: drajabr/actions-7-zip-win@main
      with:
        in: ${{ github.workspace }}\ApolloFleet
        out: ${{ github.workspace }}\ApolloFleet-${{ env.VERSION }}.exe
        options: a -sfx

    - name: Upload test build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ApolloFleet-${{ env.VERSION }}
        path: "${{ github.workspace }}\\ApolloFleet-${{ env.VERSION }}.exe"